// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleProject.API.Data;

#nullable disable

namespace SampleProject.API.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("SampleProject.API.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SampleProject.API.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "Grunge Skater Jeans",
                            Price = 68m
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "Polo Shirt",
                            Price = 35m
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Name = "Skater Graphic T-Shirt",
                            Price = 33m
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Name = "Slicker Jacket",
                            Price = 125m
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Name = "Thermal Fleece Jacket",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            Name = "Unisex Thermal Vest",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            Name = "V-Neck Pullover",
                            Price = 65m
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true,
                            Name = "V-Neck Sweater",
                            Price = 65m
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            Name = "V-Neck T-Shirt",
                            Price = 17m
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            Name = "Bamboo Thermal Ski Coat",
                            Price = 99m
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = false,
                            Name = "Cross-Back Training Tank",
                            Price = 0m
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true,
                            Name = "Grunge Skater Jeans",
                            Price = 68m
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true,
                            Name = "Slicker Jacket",
                            Price = 125m
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = true,
                            Name = "Stretchy Dance Pants",
                            Price = 55m
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true,
                            Name = "Ultra-Soft Tank Top",
                            Price = 22m
                        },
                        new
                        {
                            Id = 16,
                            IsAvailable = true,
                            Name = "Unisex Thermal Vest",
                            Price = 95m
                        },
                        new
                        {
                            Id = 17,
                            IsAvailable = true,
                            Name = "V-Next T-Shirt",
                            Price = 17m
                        },
                        new
                        {
                            Id = 18,
                            IsAvailable = true,
                            Name = "Blueberry Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 19,
                            IsAvailable = true,
                            Name = "Lemon-Lime Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 20,
                            IsAvailable = true,
                            Name = "Orange Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 21,
                            IsAvailable = true,
                            Name = "Peach Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 22,
                            IsAvailable = true,
                            Name = "Raspberry Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 23,
                            IsAvailable = true,
                            Name = "Strawberry Mineral Water",
                            Price = 2.8m
                        },
                        new
                        {
                            Id = 24,
                            IsAvailable = true,
                            Name = "In the Kitchen with H+ Sport",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 25,
                            IsAvailable = true,
                            Name = "Calcium 400 IU (150 tablets)",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 26,
                            IsAvailable = true,
                            Name = "Flaxseed Oil 100 mg (90 capsules)",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 27,
                            IsAvailable = true,
                            Name = "Iron 65 mg (150 caplets)",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 29,
                            IsAvailable = true,
                            Name = "Multi-Vitamin (90 capsules)",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 30,
                            IsAvailable = true,
                            Name = "Vitamin A 10,000 IU (125 caplets)",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 32,
                            IsAvailable = true,
                            Name = "Vitamin C 1000 mg (100 tablets)",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 28,
                            IsAvailable = true,
                            Name = "Magnesium 250 mg (100 tablets)",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 33,
                            IsAvailable = true,
                            Name = "Vitamin D3 1000 IU (100 tablets)",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 31,
                            IsAvailable = true,
                            Name = "Vitamin B-Complex (100 caplets)",
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("SampleProject.API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Tajik.WorkEmail@example.com"
                        },
                        new
                        {
                            Id = 2,
                            Email = "hggjh@example.com"
                        });
                });

            modelBuilder.Entity("SampleProject.API.Model.Order", b =>
                {
                    b.HasOne("SampleProject.API.Model.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SampleProject.API.Model.Product", b =>
                {
                    b.HasOne("SampleProject.API.Model.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("SampleProject.API.Model.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SampleProject.API.Model.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
